# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LMZChallengeSeek' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LMZChallengeSeek
  flutter_application_path = './flutter_module'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path) 

  target 'LMZChallengeSeekTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LMZChallengeSeekUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
